version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: discord-bot:latest
    container_name: "bot"
    ports:
      - "8080:8080"
    environment:
      - DISCORD_BOT_TOKEN=${TOKEN}
      - YT_EMAIL=${EMAIL}
      - YT_PASSWORD=${PASSWORD}
    volumes:
      - bot_logs:/app/log/
    networks:
      monitoring:
        aliases:
          - bot
  grafana:
    build: './config/grafana'
    container_name: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    user: root
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

  # Elasticsearch service
  es-node-01:
    container_name: es-node-01
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.0'
    networks:
      - monitoring
  # Kibana service
  kibana-01:
    container_name: kibana-01
    ports:
      - '5601:5601'
    environment:
      - 'ELASTICSEARCH_HOSTS=http://es-node-01:9200'
    image: 'docker.elastic.co/kibana/kibana:7.17.0'
    healthcheck:
      test: [ "CMD", "curl", "-f", "kibana-01:5601" ]
      interval: 50s
      timeout: 50s
      retries: 5
    depends_on:
      - es-node-01
    networks:
      - monitoring
  # Logstash service
  logstash:
    container_name: logstash-01
    volumes:
      - ./config/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./config/elk/logstash.yaml:/usr/share/logstash/config/logstash.yml:ro
    image: 'docker.elastic.co/logstash/logstash:7.16.3'
    depends_on:
      kibana-01:
        condition: service_healthy
    networks:
      - monitoring

  # Filebeat service
  filebeat:
    user: root
    container_name: filebeat-01
    command: --strict.perms=false
    volumes:
      - ./config/elk/filebeat.docker.yaml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: 'docker.elastic.co/beats/filebeat:7.16.3'
    depends_on:
      kibana-01:
        condition: service_healthy
    networks:
      - monitoring
networks:
  monitoring:
volumes:
  bot_logs: